import {useState} from 'react';
import type {FullReport} from '../engine/fortuneTypes';
import {Chart} from './Chart';
import {ReadingCard,Relations} from './Reading';
const tabs=[['summary','한눈에 보기'],['reading','사주 풀이'],['cycles','대운'],['annual','올해 · 내년'],['months','월별 흐름'],['daily','오늘의 운세']] as const;
export function Report({report,onYear,onSave,onPrint}:{report:FullReport;onYear:(year:number)=>void;onSave:()=>void;onPrint:()=>void}){
 const {natal,fortune,interpretation:reading}=report;
 const [tab,setTab]=useState<string>('summary'),[selectedCycle,setSelectedCycle]=useState<number|null>(null),[selectedMonth,setSelectedMonth]=useState<number|null>(null),[annualIndex,setAnnualIndex]=useState(0);
 const active=fortune.cycles.periods.find(p=>p.active),cycleIndex=selectedCycle??((active?.index??1)-1);
 const currentMonth=fortune.months.findIndex(p=>fortune.referenceDate>=p.startDate.slice(0,10)&&fortune.referenceDate<p.endDate.slice(0,10));
 const monthIndex=selectedMonth??Math.max(0,currentMonth),annual=fortune.annual[annualIndex];
 return <section className="report" aria-label="종합 사주 리포트">
  <div className="report-top"><span className="report-label">나의 사주 리포트</span><div className="report-actions"><button onClick={onSave}>리포트 저장</button><button onClick={onPrint}>인쇄 / PDF</button></div></div>
  <div className="report-hero"><div><p>{natal.solarDate} · {natal.input.time} · {natal.input.region}</p><h2>{natal.input.name||'나'}의 사주 이야기</h2><p>음력 {natal.lunarDate.year}.{natal.lunarDate.month}.{natal.lunarDate.day}{natal.lunarDate.intercalation?' (윤달)':''}</p></div><div className={'day-seal '+natal.pillars[2].stem.element}><b>{natal.pillars[2].stem.hanja}</b><span>{natal.pillars[2].stem.korean} · {natal.pillars[2].stem.polarity}{natal.pillars[2].stem.element}</span></div></div>
  <nav className="report-tabs" aria-label="리포트 항목">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  <div className="report-content">
  {natal.solarDate>fortune.referenceDate&&<p className="notice">입력한 출생일이 현재 조회 날짜 이후입니다. 오늘의 일진과 현재 연운은 미래 출생 원국과 비교한 자료이며 실제 생활의 운세로 단정할 수 없습니다.</p>}
  {tab==='summary'&&<><div className="welcome-reading"><span className="eyebrow">원국에서 시작하는 나의 흐름</span><h3>{reading.sections[0].title}</h3><p>{reading.intro}</p></div><div className="summary-stats"><div><small>일간</small><strong>{natal.pillars[2].stem.korean} · {natal.pillars[2].stem.element}</strong></div><div><small>현재 대운</small><strong>{active?active.stem.korean+active.branch.korean:fortune.cycles.status==='gender_required'?'성별 선택 필요':'대운 개시 전·범위 밖'}</strong></div><div><small>{fortune.referenceYear}년의 주제</small><strong>{fortune.annual[0].stemTenGod}</strong></div></div><div className="reading-grid">{reading.sections.slice(1,4).map(r=><ReadingCard key={r.id} reading={r} compact/>)}</div><button className="outline-button" onClick={()=>setTab('reading')}>내 사주 풀이 자세히 읽기 →</button><h3 className="subheading">{natal.input.name||'나'}의 만세력</h3><p className="muted">양력 {natal.solarDate} · {natal.input.time} · {natal.input.region}</p><Chart result={natal}/></>}
  {tab==='reading'&&<><div className="section-intro"><span className="eyebrow">성향에서 일상까지</span><h3>나를 이해하는 여섯 가지 관점</h3><p>일간과 십성, 원국 관계를 바탕으로 읽는 전통 규칙 해석입니다.</p></div>{reading.sections.map(r=><ReadingCard key={r.id} reading={r}/>)}<h3>원국의 합 · 충 · 형 · 파 · 해</h3><Relations items={fortune.natalRelations}/></>}
  {tab==='cycles'&&<><div className="section-intro"><span className="eyebrow">10년마다 달라지는 배경</span><h3>나의 대운 지도</h3><p>대운은 10년 단위의 간지 흐름입니다. 각 구간을 눌러 풀이를 확인하세요.</p></div>{fortune.cycles.status==='gender_required'?<div className="notice">출생 정보에서 성별을 선택한 뒤 다시 계산하면 대운 방향과 시작 시점을 확인할 수 있습니다. 다른 사주 풀이와 연운은 그대로 이용할 수 있습니다.</div>:<><div className="cycle-onset"><strong>{fortune.cycles.direction}</strong><span>대운 시작까지 {fortune.cycles.startAge!.years}년 {fortune.cycles.startAge!.months}개월 {fortune.cycles.startAge!.days}일 {fortune.cycles.startAge!.hours}시간</span><small>개시 {fortune.cycles.startDate?.slice(0,16)}</small></div><div className="cycle-scroll">{fortune.cycles.periods.map((p,i)=><button aria-pressed={cycleIndex===i} className={'cycle '+(cycleIndex===i?'selected':'')} onClick={()=>setSelectedCycle(i)} key={p.index}><small>{p.active?'현재 대운':`${p.index}대운`}</small><b>{p.ganji}</b><span>{p.stem.korean}{p.branch.korean}</span><strong>약 {p.approxAge}세부터</strong><small>{p.startDate.slice(0,4)}–{p.endDate.slice(0,4)}</small></button>)}</div><ReadingCard reading={reading.cycles[cycleIndex]}/><Relations items={fortune.cycles.periods[cycleIndex].relations}/><details><summary>대운 기산 기준</summary><p>{fortune.cycles.note}</p><p>선택한 기준일: {fortune.referenceDate}. 한 대운은 시작 시각 포함, 다음 대운 시작 시각 미포함입니다. 연도나 생일만으로 현재 대운을 판단하지 않습니다.</p></details></>}</>}
  {tab==='annual'&&<><div className="section-intro"><span className="eyebrow">입춘부터 시작하는 한 해</span><h3>연간 운세 리포트</h3><p>올해와 내년의 간지가 원국과 맺는 관계를 살펴봅니다.</p></div><div className="year-controls"><label>조회 연도<select value={fortune.referenceYear} onChange={e=>{onYear(Number(e.target.value));setAnnualIndex(0);setSelectedMonth(null);}}>{Array.from({length:21},(_,i)=>Math.min(2119,Math.max(1960,Number(fortune.referenceDate.slice(0,4))))-10+i).map(y=><option key={y} value={y}>{y}년</option>)}</select></label><div className="segmented">{fortune.annual.map((p,i)=><button key={p.year} className={annualIndex===i?'selected':''} onClick={()=>setAnnualIndex(i)}>{p.year}년</button>)}</div></div><div className="luck-banner"><span>{annual.stem.korean}{annual.branch.korean}년</span><b>{annual.ganji}</b><p>{annual.stemTenGod} · {annual.branchTenGod}</p></div><ReadingCard reading={reading.annual[annual.year]}/><Relations items={[...annual.relations,...annual.cycleRelations]}/><p className="fineprint">{annual.startDate}부터 {annual.endDate} 직전까지 · 서머타임을 제거한 한국 표준시</p></>}
  {tab==='months'&&<><div className="section-intro"><span className="eyebrow">계절의 변화를 따라</span><h3>{fortune.referenceYear}년 월별 흐름</h3><p>달력의 1~12월 대신 입춘에서 소한까지, 실제 절입 시각으로 구분합니다.</p></div><div className="month-grid">{fortune.months.map((p,i)=><button aria-pressed={monthIndex===i} className={monthIndex===i?'selected':''} key={i} onClick={()=>setSelectedMonth(i)}><small>{p.startDate.slice(5,10)}</small><strong>{p.term}</strong><span>{p.stem.korean}{p.branch.korean}</span><small>{p.stemTenGod}</small></button>)}</div><ReadingCard reading={reading.months[monthIndex]}/><p className="fineprint">절입 시각: {fortune.months[monthIndex].startDate} ~ {fortune.months[monthIndex].endDate} 직전</p><Relations items={fortune.months[monthIndex].relations}/></>}
  {tab==='daily'&&<><div className="section-intro"><span className="eyebrow">오늘을 돌아보는 작은 힌트</span><h3>{fortune.referenceDate} 오늘의 운세</h3><p>한국 날짜의 일진과 내 원국의 관계를 참고해 하루의 주제를 살펴보세요.</p></div><div className="luck-banner"><span>{fortune.daily.stem.korean}{fortune.daily.branch.korean}일</span><b>{fortune.daily.ganji}</b><p>{fortune.daily.stemTenGod} · {fortune.daily.branchTenGod}</p></div><ReadingCard reading={reading.daily}/><Relations items={fortune.daily.relations}/><p className="fineprint">{fortune.methods[2]}</p></>}
  <div className="report-footnote"><strong>풀이를 읽는 기준</strong><p>계산 데이터에 전통 해석 규칙을 적용한 참고용 리포트입니다. 타고난 성격이나 미래의 사건을 확정하지 않습니다. 신강·신약과 용신·희신 판정은 아직 제공하지 않습니다.</p><details><summary>해석 방식과 계산 범위</summary><ul>{[...reading.limitations,...fortune.methods].map((s,i)=><li key={i}>{s}</li>)}</ul></details></div>
  </div>
 </section>;
}
