import {test,expect} from '@playwright/test';
import {openFullReport} from './helpers';
test('첫 화면 공통 일진은 출생정보 없이 바로 표시',async({page})=>{await page.goto('/');await expect(page.getByLabel('생년월일')).toHaveValue('');await page.getByRole('button',{name:'입력 없이 오늘의 공통 흐름 보기',exact:true}).click();await expect(page.locator('.common-daily')).toBeVisible();await expect(page.getByText('공통 일진 · 개인별 운세 아님',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'종합 사주 리포트'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('누구의 정보든 넣으면 개인 오늘 운세로 바로 이동, 다른 사람은 독립 계산',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'개인별 오늘 운세 바로 보기 →',exact:true}).click();await page.getByLabel('이름').fill('첫사람');await page.getByLabel('생년월일').fill('1988-01-03');await page.getByLabel('출생시간').fill('12:00');await page.getByRole('button',{name:'오늘 운세 바로 보기',exact:true}).click();
 await openFullReport(page);const report=page.getByRole('region',{name:'종합 사주 리포트'});await expect(report.getByRole('heading',{name:'첫사람의 오늘 운세',exact:true})).toBeVisible();await expect(report.getByRole('button',{name:'오늘의 운세',exact:true})).toHaveAttribute('aria-pressed','true');await expect(report.getByRole('heading',{name:'오늘의 일진 풀이'})).toBeVisible();
 const first=page.waitForEvent('download');await page.getByRole('button',{name:'리포트 저장',exact:true}).click();const fs=await import('node:fs/promises');const a=JSON.parse(await fs.readFile((await (await first).path())!,'utf8'));
 await page.getByRole('button',{name:'다른 사람 입력',exact:true}).click();await expect(page.getByLabel('생년월일')).toHaveValue('');await expect(page.getByLabel('이 기기에 출생정보 저장')).not.toBeChecked();await page.getByLabel('이름').fill('둘째사람');await page.getByLabel('생년월일').fill('1988-01-04');await page.getByLabel('출생시간').fill('12:00');await page.getByRole('button',{name:'오늘 운세 바로 보기',exact:true}).click();await openFullReport(page);await expect(report.getByRole('heading',{name:'둘째사람의 오늘 운세',exact:true})).toBeVisible();await expect(report.getByText('첫사람',{exact:false})).toHaveCount(0);
 const second=page.waitForEvent('download');await page.getByRole('button',{name:'리포트 저장',exact:true}).click();const b=JSON.parse(await fs.readFile((await (await second).path())!,'utf8'));expect(b.natal.solarDate).toBe('1988-01-04');expect(a.fortune.daily.ganji).toBe(b.fortune.daily.ganji);expect(a.fortune.daily.stemTenGod).not.toBe(b.fortune.daily.stemTenGod);expect(await page.evaluate(()=>localStorage.getItem('saju-garden-birth-v1'))).toBeNull();
});
test('오늘 운세 전용 링크와 숨겨진 근거/해석 범위',async({page})=>{await page.goto('/?view=today');await expect(page.locator('.common-daily')).toBeVisible();await page.getByLabel('생년월일').fill('1988-01-03');await page.getByLabel('출생시간').fill('12:00');await page.getByRole('button',{name:'오늘 운세 바로 보기',exact:true}).click();await openFullReport(page);await page.getByRole('region',{name:'종합 사주 리포트'}).getByRole('button',{name:'사주 풀이',exact:true}).click();const wealth=page.locator('#report-anchor .reading-card').filter({has:page.getByRole('heading',{name:'재물 · 자원의 흐름'})});await expect(wealth).toContainText('곶감');await expect(wealth.locator('.reading-notes')).toBeHidden();await wealth.getByText('이 풀이의 계산 근거',{exact:true}).click();await expect(wealth.locator('.reading-notes')).toBeVisible();});
