import {test,expect} from '@playwright/test';
async function create(page:import('@playwright/test').Page,gender='남성'){
 await page.goto('/');await page.getByLabel('이름').fill('정원');await page.getByLabel('성별',{exact:true}).selectOption(gender);await page.getByLabel('생년월일').fill('1988-07-12');await page.getByRole('button',{name:'사주 원국 계산하기'}).click();await expect(page.getByRole('heading',{name:'정원의 사주 이야기'})).toBeVisible();
}
test('모바일 종합 리포트: 풀이·대운·연운·월운·일진',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await create(page);
 await page.getByRole('button',{name:'사주 풀이',exact:true}).click();await expect(page.getByRole('heading',{name:'나를 이해하는 여섯 가지 관점'})).toBeVisible();await expect(page.getByRole('heading',{name:'재물 · 자원의 흐름'})).toBeVisible();
 await page.getByRole('button',{name:'대운',exact:true}).click();await expect(page.getByRole('heading',{name:'나의 대운 지도'})).toBeVisible();await expect(page.locator('.cycle')).toHaveCount(10);await page.locator('.cycle').first().click();await expect(page.locator('.cycle').first()).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('heading',{name:/1대운 ·/})).toBeVisible();
 await page.getByRole('button',{name:'올해 · 내년',exact:true}).click();await expect(page.getByRole('heading',{name:'연간 운세 리포트'})).toBeVisible();await page.getByLabel('조회 연도').selectOption('2030');await expect(page.locator('.luck-banner')).toContainText('庚戌');await page.getByRole('button',{name:'2031년',exact:true}).click();await expect(page.locator('.luck-banner')).toContainText('辛亥');
 await page.getByRole('button',{name:'월별 흐름',exact:true}).click();await expect(page.locator('.month-grid button')).toHaveCount(12);await page.locator('.month-grid button').nth(5).click();await expect(page.getByRole('heading',{name:'소서부터의 월운'})).toBeVisible();
 await page.getByRole('button',{name:'오늘의 운세',exact:true}).click();await expect(page.getByRole('heading',{name:'오늘의 일진 풀이'})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'리포트 저장',exact:true}).click();const file=await download;expect(file.suggestedFilename()).toBe('saju-report.json');
 const path=await file.path();const fs=await import('node:fs/promises');const data=JSON.parse(await fs.readFile(path!,'utf8'));expect(data.schemaVersion).toBe('2.0');expect(data.fortune.cycles.periods).toHaveLength(10);expect(data.interpretation.sections).toHaveLength(6);expect(data.fortune.referenceYear).toBe(2030);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('성별 미선택은 대운 계산 보류, 다른 풀이 유지',async({page})=>{await create(page,'선택 안 함');await page.getByRole('button',{name:'대운',exact:true}).click();await expect(page.getByText('출생 정보에서 성별을 선택한 뒤 다시 계산하면',{exact:false})).toBeVisible();await expect(page.locator('.cycle')).toHaveCount(0);await page.getByRole('button',{name:'사주 풀이',exact:true}).click();await expect(page.getByRole('heading',{name:'직업 · 일하는 방식'})).toBeVisible();});
test('기기 저장은 직접 선택하고 삭제할 수 있음',async({page})=>{await page.goto('/');await page.getByLabel('생년월일').fill('1988-07-12');await page.getByLabel('이 기기에 출생정보 저장').check();await page.getByRole('button',{name:'사주 원국 계산하기'}).click();await expect(page.getByRole('status')).toContainText('출생정보를 저장');await page.reload();await page.getByRole('button',{name:'저장한 정보 불러오기'}).click();await expect(page.getByLabel('생년월일')).toHaveValue('1988-07-12');await page.getByRole('button',{name:'저장 삭제',exact:true}).click();await page.reload();await page.getByRole('button',{name:'저장한 정보 불러오기'}).click();await expect(page.getByRole('status')).toContainText('없습니다');});
test('인쇄는 전체 리포트를 제공하고 입력정보 저장을 기본으로 켜지 않음',async({page})=>{await create(page);expect(await page.evaluate(()=>localStorage.getItem('saju-garden-birth-v1'))).toBeNull();await page.emulateMedia({media:'print'});await expect(page.locator('.input-panel')).toBeHidden();await expect(page.locator('.print-report')).toBeVisible();await expect(page.locator('.print-report').getByRole('heading',{name:'올해와 내년',exact:true})).toBeVisible();await expect(page.locator('.print-report .print-cycles>div')).toHaveCount(10);const pdf=await page.pdf({format:'A4'});expect(pdf.length).toBeGreaterThan(10000);await page.emulateMedia({media:'screen'});});
