import type {SajuResult} from '../engine/types';
import type {FortuneData,ReadingSection} from '../engine/fortuneTypes';
import type {GodGroup,GodSource} from '../engine/profile';
import {traits,gods,family} from './themes';
const locations=(sources:GodSource[])=>[...new Set(sources.map(s=>`${s.position}의 ${s.god}`))].join(', ');
const groupNames:Record<GodGroup,string>={비겁:'내 기준과 동료를 보는 비겁',식상:'표현하고 만들어내는 식상',재성:'돈과 자원을 다루는 재성',관성:'약속과 책임을 보는 관성',인성:'배움과 도움을 보는 인성'};
const work:Record<string,string>={비견:'자신의 담당 영역이 분명하고 동료와 동등하게 협의하는 역할',겁재:'사람을 모으고 역할을 나누는 협업·조율 역할',식신:'품질과 반복 경험을 쌓아 결과물을 만드는 제작·운영 역할',상관:'문제를 찾아 개선하고 새로운 표현을 만드는 기획·콘텐츠 역할',편재:'사람과 자원을 연결하는 영업·사업개발·프로젝트 역할',정재:'비용·일정·자료를 꾸준히 관리하는 실무·운영 역할',편관:'어려운 과제를 다루되 권한과 지원 체계를 분명히 갖춘 역할',정관:'기준과 약속을 관리하는 조직 운영·품질·행정 역할',편인:'새로운 분야를 조사하고 관점을 제안하는 연구·기획 역할',정인:'지식을 체계화하고 전달하는 교육·분석·지원 역할'};
const relationStyle:Record<string,string>={비견:'서로의 선택과 영역을 존중하는 동등한 관계',겁재:'함께 움직이되 돈과 역할의 경계는 명확히 하는 관계',식신:'일상의 편안함과 꾸준한 표현을 함께 만드는 관계',상관:'생각을 솔직하게 나누면서 표현의 방식도 조율하는 관계',편재:'함께 경험을 넓히면서 시간과 비용의 기준을 공유하는 관계',정재:'생활의 약속과 작은 신뢰를 꾸준히 쌓는 관계',편관:'서로에게 요구하는 수준과 감당할 수 있는 책임을 나누는 관계',정관:'약속과 기준을 분명히 하면서 서로의 입장도 듣는 관계',편인:'각자의 관심과 혼자 생각할 시간을 존중하는 관계',정인:'서로 배우고 정서적 지원을 주고받는 관계'};
export function buildNatalReadings(natal:SajuResult,fortune:FortuneData):ReadingSection[]{
 const profile=fortune.profile,day=natal.pillars[2].stem,month=natal.pillars[1],trait=traits[day.hanja],name=natal.input.name||'당신';
 function groupText(group:GodGroup){const {visible,hidden}=profile.groups[group];
  if(visible.length&&hidden.length)return `${groupNames[group]}은 ${locations(visible)}에 보이고, 속에 담긴 ${locations(hidden)}에도 있어요. 겉모습과 안에 든 재료를 함께 봐야 하는 부분이에요.`;
  if(visible.length)return `${groupNames[group]}은 ${locations(visible)}에 보이는 글자예요.`;
  if(hidden.length)return `${groupNames[group]}은 겉에 바로 보이지 않지만 ${locations(hidden)}의 지장간, 그러니까 지지 안에 담긴 글자에 있어요. 서랍 안에 챙겨둔 재료처럼 함께 살펴볼 부분이에요.`;
  return `${groupNames[group]} 글자는 겉과 속을 함께 살펴봐도 없어요. 이 주제를 일상의 연습과 약속으로 챙겨보는 관점이 도움이 돼요.`;
 }
 const groupEvidence=(...groups:GodGroup[])=>groups.flatMap(g=>[...profile.groups[g].visible,...profile.groups[g].hidden].map(s=>`${s.position} ${s.layer} ${s.hanja}: ${s.god}`));
 const rootText=profile.roots.length?`${day.korean}${day.element}와 같은 오행의 뿌리는 ${profile.roots.map(r=>`${r.position}의 ${natal.pillars.find(p=>p.label===r.position)!.branch.korean} 속`).join(', ')}에 있어요. 겉에 보이는 글자가 속에서도 기댈 자리를 가진 모습으로 생각하면 쉬워요.`:`일간 ${day.korean}${day.element}와 같은 오행의 지장간은 원국에 없어요. 이때는 내 방식만 바라보기보다 주변 환경과 맡은 역할을 함께 살펴보는 관점으로 읽어요.`;
 const seasonText=`태어난 달의 지지는 ${month.branch.korean}, 계절은 ${profile.season}이에요. 같은 씨앗도 어느 계절에 놓이느냐가 다르듯 태어난 달을 함께 봐야 해요. 월지의 중심 글자는 ${profile.monthMainGod}인데, ${gods[profile.monthMainGod].meaning}`;
 const wealth=[...profile.groups.재성.visible,...profile.groups.재성.hidden],output=[...profile.groups.식상.visible,...profile.groups.식상.hidden];
 const direct=wealth.filter(s=>s.god==='정재'),opportunity=wealth.filter(s=>s.god==='편재');
 const wealthStyle=direct.length&&opportunity.length?'정재와 편재가 함께 있어요. 정재는 늘 챙기는 살림돈, 편재는 장터에서 새 기회를 찾는 모습에 비유할 수 있어요. 살림돈과 새 일을 해보는 돈을 나누어두면 두 주제를 함께 다루기 쉬워요.':direct.length?'정재는 곶감을 하나씩 꿰어두듯 차곡차곡 챙기는 글자예요. 들어오는 돈과 나가는 돈의 자리를 정하고, 반복할 수 있는 수입·지출의 틀을 만드는 관점으로 읽어요.':opportunity.length?'편재는 장터에서 필요한 사람과 재료를 이어주는 모습과 닮았어요. 새로운 거래나 프로젝트를 살펴볼 때 사람과의 인연, 계약의 조건, 들어갈 돈을 각각 나누어 챙겨보세요.':'재성 글자가 없다고 돈을 벌 수 없다는 뜻은 아니에요. 타고난 글자 설명에 기대기보다, 돈이 들어오는 길과 남겨두는 방법을 생활 속에서 차근히 만드는 관점으로 읽어요.';
 const outputText=output.length&&wealth.length?`식상도 ${locations(output)}에 있어요. 식상은 내가 만들어내는 솜씨, 재성은 그것을 필요한 곳에 건네고 관리하는 모습으로 비유할 수 있어요. 자신의 기술과 결과물을 어떤 일이나 거래에 연결할지 살펴보세요.`:output.length?`식상은 ${locations(output)}에 있어요. 결과물을 만드는 주제는 보이니, 만든 것을 누구에게 어떻게 건넬지 가격·일정·약속으로 이어보세요.`:'식상은 지장간까지 살펴봐도 없어요. 솜씨나 표현력이 없다는 말은 아니에요. 만든 것을 보여주고 반응을 듣는 작은 경험을 의식적으로 쌓아보는 관점이 좋아요.';
 const strongest=Object.entries(profile.groups).sort((a,b)=>b[1].visible.length-a[1].visible.length)[0][0] as GodGroup;
 const careerText=`일하는 환경을 보는 월지의 중심은 ${profile.monthMainGod}이에요. 일을 하나 맡는다면 ${work[profile.monthMainGod]}의 모습을 떠올려보세요. 원국에는 ${strongest} 글자가 겉에 가장 많이 보여서, ${gods[([...profile.groups[strongest].visible][0]?.god)||profile.monthMainGod].theme}라는 이야기도 함께 읽을 수 있어요.`;
 const supportGroups=(['인성','식상','관성'] as GodGroup[]).filter(g=>g!==family(profile.monthMainGod));
 const relationship=natal.pillars[2],close=fortune.natalRelations.filter(r=>r.left==='일주'||r.right==='일주'),clashes=close.filter(r=>r.type==='충'),joins=close.filter(r=>r.type==='육합'||r.type==='천간합'),self=close.filter(r=>r.type==='형'&&r.pair[0]===r.pair[1]);
 const closeText=clashes.length?`${clashes.map(r=>`${r.left}와 ${r.right}의 ${r.pair}충`).join(', ')}이 있어 가까운 관계의 기준과 다른 자리의 요구를 함께 조율하는 부분을 함께 챙겨보면 좋아요. 약속을 바꿔야 할 때는 결론보다 이유와 일정부터 공유해보세요.`:joins.length?`${joins.map(r=>`${r.left}와 ${r.right}의 ${r.pair}${r.type}`).join(', ')}이 있어요. 관계와 다른 생활 영역이 이어지는 모습으로 읽을 수 있어요. 연결을 유지하되 자신의 기준과 상대의 기대를 구분하면 균형을 잡기 쉬워요.`:self.length?`${self.map(r=>r.pair+' 자형').join(', ')}처럼 같은 지지가 반복돼요. 바느질한 곳을 여러 번 되짚듯 같은 기준을 다시 살피는 이미지예요. 혼자 곱씹은 내용을 대화로 한번 확인해보세요.`:'일주와 다른 기둥 사이에는 천간합·육합·충이 없어요. 일지 본기의 관계 방식에 집중해, 실제 대화에서 어떤 약속을 중요하게 여기는지 살펴보세요.';
 const wholeClashes=fortune.natalRelations.filter(r=>r.type==='충');
 const transitions=wholeClashes.length?`원국에는 ${wholeClashes.map(r=>`${r.left}·${r.right} ${r.pair}충`).join(', ')}이 있어요. 서로 다른 방향의 두 사람이 한 길을 걷는 모습에 비유할 수 있어요. 일과 생활, 가까운 관계의 일정이 겹칠 때 어떤 기준을 먼저 챙길지 이야기해보세요.`:'원국에는 쌍별 지지 충이 없어요. 다만 길에 새 사람이 합류하듯 대운과 연운의 글자가 들어오면 새로운 관계가 생겨요. 변화의 흐름은 각 운의 구간을 함께 살펴보면 좋아요.';
 const visibleElements=Object.entries(natal.elementCounts).filter(([,n])=>n>0).map(([e,n])=>`${e} ${n}`).join(' · '),hiddenOnly=Object.entries(profile.elementLocations).filter(([,v])=>!v.length).map(([e])=>{const sources=natal.pillars.flatMap(p=>p.hiddenStems.filter(s=>s.element===e).map(s=>`${p.label} ${p.branch.hanja} 속 ${s.hanja}`));return sources.length?`${e}은 겉에 보이는 여덟 글자에는 없지만 ${sources.join(', ')}에 담겨 있어요.`:`${e}은 속에 담긴 글자까지 살펴봐도 없어요.`;});
 return [
 {id:'nature',title:trait.title,subtitle:`${day.korean}${day.element} 일간 · ${profile.season}의 월지`,paragraphs:[`${name}의 일간은 ${day.korean}${day.element}, ${trait.image}에 빗대어 읽어요. ${trait.strength}`,seasonText,rootText,trait.balance],evidence:[`일간 ${day.hanja} ${day.polarity}${day.element}`,`월지 ${month.branch.hanja}, 본기 ${month.hiddenStems[0].hanja} ${profile.monthMainGod}`,...profile.roots.map(r=>`${r.position} ${r.branch}: 동오행 지장간 ${r.stems.join('·')}`)],notes:['계절과 통근은 구조 자료이며 이것만으로 신강·신약이나 용신을 확정하지 않습니다.'],actions:[gods[profile.monthMainGod].action,trait.balance]},
 {id:'wealth',title:'재물 · 자원의 흐름',subtitle:direct.length&&opportunity.length?'꾸준한 관리와 기회를 함께 다루는 구조':direct.length?'꾸준히 쌓고 관리하는 재성':opportunity.length?'사람과 기회를 연결하는 재성':'자원을 운영하는 체계를 살펴보기',paragraphs:[groupText('재성'),wealthStyle,outputText],evidence:groupEvidence('재성','식상'),notes:['식상과 재성이 함께 있다는 것은 배속의 존재를 뜻하며, 식상생재 격국 성립이나 실제 수입 증가의 판정은 아닙니다.'],actions:[direct.length?'반복 수입·고정 지출·축적 목표를 같은 장부에 정리해보세요.':'새로운 거래는 상대와의 관계, 계약 조건, 사용 자금을 따로 정리해보세요.',output.length?'자신이 만든 결과물을 보여줄 방법과 대가를 받는 조건을 한 가지씩 정해보세요.':'정해진 주기로 결과물과 피드백을 남기는 루틴을 마련해보세요.']},
 {id:'career',title:'직업 · 일하는 방식',subtitle:`월지 ${profile.monthMainGod} 중심의 역할과 환경`,paragraphs:[careerText,...supportGroups.map(groupText)],evidence:[`월지 본기 ${month.hiddenStems[0].hanja} ${profile.monthMainGod}`,...groupEvidence('관성','인성','식상')],notes:['예시 역할은 전통 십성의 상징을 업무 방식으로 풀어쓴 것이며 특정 직업의 적합성을 확정한 판정은 아닙니다.'],actions:[`${work[profile.monthMainGod]}에서 자신의 강점과 실제 경험이 맞닿는 부분을 적어보세요.`,profile.groups.관성.visible.length?'맡을 책임뿐 아니라 사용할 권한과 지원도 확인해보세요.':'업무의 목표·평가 기준·마감을 먼저 합의하면 일하는 방식이 선명해집니다.']},
 {id:'relationship',title:'관계 · 배우자',subtitle:`일지 ${relationship.branch.korean} · ${relationship.branchTenGod}의 관계 방식`,paragraphs:[`가까운 관계를 보는 자리는 일지 ‘${relationship.branch.korean}’이에요. 그 안의 중심 글자는 ${relationship.branchTenGod}이에요. ${relationStyle[relationship.branchTenGod]}를 중심으로 읽을 수 있어요.`,closeText,`${groupText('비겁')} 가까운 관계에서도 자신의 영역과 함께하는 영역을 구분해 살펴보세요.`],evidence:[`일지 ${relationship.branch.hanja}, 본기 ${relationship.hiddenStems[0].hanja} ${relationship.branchTenGod}`,...close.map(r=>`${r.left} ↔ ${r.right}: ${r.pair} ${r.type}`)],notes:['배우자의 직업·성격이나 결혼 시기를 확정하지 않으며, 궁합은 상대의 원국이 있어야 별도로 검토할 수 있습니다.'],actions:[gods[relationship.branchTenGod].action,'시간·돈·연락에 대해 기대하는 기준을 한 번에 하나씩 나눠보세요.']},
 {id:'change',title:'변화 · 이동의 관점',subtitle:wholeClashes.length?'서로 다른 기준을 조율하는 변화':'대운과 연운을 함께 보는 변화',paragraphs:[transitions,`지금 대운은 ${fortune.cycles.periods.find(p=>p.active)?.ganji||'성별 미선택 또는 개시 전·표시 범위 밖'}이에요. 연운 ${fortune.annual[0].ganji}과 원국의 관계는 올해·내년 탭에서, 대운과 원국의 관계는 대운 탭에서 차근차근 함께 볼 수 있어요.`],evidence:fortune.natalRelations.map(r=>`${r.left} ↔ ${r.right}: ${r.pair} ${r.type}`),notes:['쌍별 충이나 형을 실제 이사·이직·사고의 발생으로 판정하지 않습니다.'],actions:[wholeClashes.length?'일과 생활에서 동시에 바꿔야 할 일을 나누고 우선순위를 정해보세요.':'변화를 계획한다면 현재 대운과 해당 연운의 구간을 나누어 살펴보세요.']},
 {id:'elements',title:'오행 · 생활의 균형',subtitle:'표면의 오행과 지장간을 함께 읽기',paragraphs:[`겉에 보이는 여덟 글자의 오행은 ${visibleElements}이에요. 태어난 계절은 ${profile.season}, 일간은 ${day.polarity}${day.element}이에요.`,...hiddenOnly,rootText],evidence:Object.entries(profile.elementLocations).flatMap(([e,v])=>v.map(p=>`${e}: ${p}`)),notes:['오행의 단순 개수·계절·동오행 통근 자료만으로 신강·신약, 용신·희신을 판정하지 않습니다. 그 판정은 미구현입니다.'],actions:['표면에 없는 오행과 지장간에도 없는 오행을 구분해 리포트를 읽어보세요.']},
 ];
}
